Add potato annotation tool
zenml-io/awesome-open-data-annotation pull request #9
Opened 2023-07-07 16:39 UTC by Jiaxin-Pei

2023-07-07 20:08 UTC, strickvl requested changes
Thanks for this contribution. Some small changes, but otherwise this looks good to me!

2023-07-07 20:08 UTC, strickvl commented on README.md
> +| [Potato](https://github.com/davidjurgens/potato) | An annotation framework with 20+ tempaltes, editable UI, quality control, data management and even add a surveyflow for crowdourcing ![](https://i
```suggestion
```

2023-07-07 20:08 UTC, strickvl commented on README.md
> +| [Potato](https://github.com/davidjurgens/potato) | An annotation framework with 20+ tempaltes, editable UI, quality control, data management and even add a surveyflow for crowdourcing ![](https://i
```suggestion
| [Potato](https://github.com/davidjurgens/potato) | An annotation framework with 20+ templates, editable UI, quality control, data management and an option to add a survey for crowdsourcing ![](https://img.shields.io/github/stars/davidjurgens/potato?color=black&label=%E2%AD%90%EF%B8%8F&style=plastic) | PolyForm Shield |
```

2023-07-08 14:32 UTC, Jiaxin-Pei commented
Thanks! I just committed the changes you suggested!

2023-07-08 16:15 UTC, strickvl approved these changes

2023-07-08 16:15 UTC, merged